In [54]:
from sklearn import datasets

# Importing iris dataset

In [55]:
iris=datasets.load_iris()

In [56]:
type(iris)

sklearn.utils.Bunch

In [57]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [58]:
iris["filename"]

'C:\\Users\\AkhilNikhil\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'

In [6]:
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
print(iris["DESCR"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
print(type(iris["data"]))
print(type(iris["target"]))
print(type(iris["feature_names"]))
print(type(iris["DESCR"]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'str'>


In [11]:
X=iris.data

In [12]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
y=iris.target

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Converting to dataframe

In [23]:
import pandas as pd
df=pd.DataFrame(data=iris["data"],columns=iris["feature_names"])
df.iloc[[0,50,100]]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
50                 7.0               3.2                4.7               1.4
100                6.3               3.3                6.0               2.5

In [24]:
df["target"]=iris.target

In [25]:
df.iloc[[0,50,100]]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
100                6.3               3.3                6.0               2.5   

     target  
0         0  
50        1  
100       2

In [32]:
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [33]:
df.target.replace([0,1,2],['setosa', 'versicolor', 'virginica'],inplace=True)

In [34]:
df.iloc[[0,50,100]]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
100                6.3               3.3                6.0               2.5   

         target  
0        setosa  
50   versicolor  
100   virginica

In [36]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

# Implementing KNN

In [37]:
#euclidean distance
import numpy as np

def ed(known_samples,unknown_samples):
    distance=0
    for i in range(len(known_samples)-1):
        distance += (known_samples[i]-unknown_samples[i])**2
    return np.sqrt(distance)

In [38]:
df_np=df.values

In [39]:
unknown_samples=[[5.1,3.5,1.4,0.2],[7.0,3.2,4.7,1.4],[6.3,3.3,6.0,2.5]]

In [41]:
#calculating the nearest neighbors
def get_neigbors(known_sample,unknown_sample,n_neighbors):
    distances=[]
    for ks in known_sample:
        dist=ed(ks,unknown_sample)
        distances.append((ks,dist))
    distances.sort(key=lambda tup:tup[1])
    neighbors=[]
    for i in range(n_neighbors):
        neighbors.append(distances[i][0])
    return neighbors    

In [42]:
get_neigbors(df_np,unknown_samples[0],3)

[array([5.1, 3.5, 1.4, 0.2, 'setosa'], dtype=object),
 array([5.1, 3.5, 1.4, 0.3, 'setosa'], dtype=object),
 array([5.0, 3.6, 1.4, 0.2, 'setosa'], dtype=object)]

In [43]:
get_neigbors(df_np,unknown_samples[1],3)

[array([7.0, 3.2, 4.7, 1.4, 'versicolor'], dtype=object),
 array([6.9, 3.1, 4.9, 1.5, 'versicolor'], dtype=object),
 array([6.7, 3.1, 4.7, 1.5, 'versicolor'], dtype=object)]

In [44]:
get_neigbors(df_np,unknown_samples[2],3)

[array([6.3, 3.3, 6.0, 2.5, 'virginica'], dtype=object),
 array([6.3, 3.4, 5.6, 2.4, 'virginica'], dtype=object),
 array([6.7, 3.3, 5.7, 2.5, 'virginica'], dtype=object)]

In [52]:
#making prediction
def predict(known_sample,unknown_sample,n_neighbors):
    rs=[]
    for uks in unknown_sample:
        neighbors=get_neigbors(known_sample,uks,n_neighbors)
        output_values=[row[-1] for row in neighbors]
        prediction=max(set(output_values),key=output_values.count)
        rs.append(prediction)
    return rs

In [53]:
predict(df_np,unknown_samples,4)

['setosa', 'versicolor', 'virginica']